In [1]:
import math
import pandas as pd
import numpy as np
import pymysql

In [2]:
df = pd.read_csv('COVID_monthly_data.csv')
df.head()

,Country,month_date,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,total_vaccinated,total_fully_vaccinated
0,Afghanistan,2020-02-29,5,0,0.126,0.000,0,0
1,Afghanistan,2020-03-31,5,0,0.126,0.000,0,0
2,Afghanistan,2020-04-30,192,4,4.820,0.100,0,0
3,Afghanistan,2020-05-31,2171,64,54.499,1.607,0,0
4,Afghanistan,2020-06-30,15836,269,397.536,6.753,0,0

In [3]:
df1 = df.copy()

In [4]:
df1.head(50)

,Country,month_date,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,total_vaccinated,total_fully_vaccinated
0,Afghanistan,2020-02-29,5,0,0.126,0.000,0,0
1,Afghanistan,2020-03-31,5,0,0.126,0.000,0,0
2,Afghanistan,2020-04-30,192,4,4.820,0.100,0,0
3,Afghanistan,2020-05-31,2171,64,54.499,1.607,0,0
4,Afghanistan,2020-06-30,15836,269,397.536,6.753,0,0
5,Afghanistan,2020-07-31,31848,778,799.489,19.530,0,0
6,Afghanistan,2020-08-31,36796,1287,923.700,32.308,0,0
7,Afghanistan,2020-09-30,38282,1410,961.004,35.396,0,0
8,Afghanistan,2020-10-31,39371,1462,988.341,36.701,0,0
9,Afghanistan,2020-11-30,41425,1536,1039.900,38.559,0,0
10,Afghanistan,2020-12-31,46498,1774,1167.250,44.533,0,0
11,Afghanistan,2021-01-31,52513,2201,1318.250,55.252,0,0
12,Afghanistan,2021-02-28,55059,2404,1382.160,60.348,8200,0
13,Afghanistan,2021-03-31,55733,2444,1399.080,61.352,54000,0
14,Afghanistan,2021-04-30,56517,2489,1418.760,62.482,240000,0
15,Afghanistan,2021-05-31,59939,2631,1504.670,66.047,480226,119926
16,Afghanistan,2021-06-30,72977,2973,1831.960,74.632,699200,187654
17,Afghanistan,2021-07-31,120216,4962,3017.820,124.562,742934,219159
18,Afghanistan,2021-08-31,147501,6737,3702.760,169.121,773002,430744
19,Afghanistan,2021-09-30,153260,7123,3847.330,178.811,828601,0
20,Afghanistan,2021-10-31,155191,7206,3895.800,180.894,0,0
21,Afghanistan,2021-11-30,156284,7281,3923.240,182.777,3530173,3188609
22,Afghanistan,2021-12-31,157359,7309,3950.230,183.480,4142857,3753224
23,Afghanistan,2022-01-31,158107,7356,3969.000,184.660,4554648,3892831
24,Afghanistan,2022-02-28,163555,7417,4105.770,186.191,4907058,4231984
25,Afghanistan,2022-03-31,173879,7609,4364.930,191.011,0,0
26,Albania,2020-02-29,0,0,0.000,0.000,0,0
27,Albania,2020-03-31,0,0,0.000,0.000,0,0
28,Albania,2020-04-30,259,15,90.152,5.221,0,0
29,Albania,2020-05-31,782,31,272.196,10.790,0,0
30,Albania,2020-06-30,1143,33,397.851,11.487,0,0
31,Albania,2020-07-31,2580,65,898.037,22.625,0,0
32,Albania,2020-08-31,5396,161,1878.220,56.040,0,0
33,Albania,2020-09-30,9606,290,3343.620,100.942,0,0
34,Albania,2020-10-31,13806,388,4805.540,135.054,0,0
35,Albania,2020-11-30,21202,518,7379.910,180.303,0,0
36,Albania,2020-12-31,39014,822,13579.800,286.119,0,0
37,Albania,2021-01-31,58316,1181,20298.400,411.078,549,0
38,Albania,2021-02-28,78992,1393,27495.200,484.870,6073,655
39,Albania,2021-03-31,107931,1816,37568.200,632.106,0,0
40,Albania,2021-04-30,125506,2241,43685.700,780.039,0,0
41,Albania,2021-05-31,131185,2396,45662.400,833.991,486128,290333
42,Albania,2021-06-30,132337,2451,46063.400,853.135,564530,403504
43,Albania,2021-07-31,132523,2456,46128.100,854.875,670215,528718
44,Albania,2021-08-31,133121,2457,46336.300,855.223,830396,641920
45,Albania,2021-09-30,147369,2501,51295.600,870.539,946495,794878
46,Albania,2021-10-31,170778,2705,59443.800,941.546,1013959,887865
47,Albania,2021-11-30,185497,2931,64567.100,1020.210,1072645,961013
48,Albania,2021-12-31,200173,3101,69675.500,1079.380,1141486,1031132
49,Albania,2022-01-31,210224,3217,73174.000,1119.760,1210040,1111520

In [5]:
df1.total_vaccinated.replace(0, np.nan, inplace=True)
df1.total_fully_vaccinated.replace(0, np.nan, inplace=True)

In [6]:
df1

,Country,month_date,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,total_vaccinated,total_fully_vaccinated
0,Afghanistan,2020-02-29,5,0,0.126,0.000,NaN,NaN
1,Afghanistan,2020-03-31,5,0,0.126,0.000,NaN,NaN
2,Afghanistan,2020-04-30,192,4,4.820,0.100,NaN,NaN
3,Afghanistan,2020-05-31,2171,64,54.499,1.607,NaN,NaN
4,Afghanistan,2020-06-30,15836,269,397.536,6.753,NaN,NaN
...,...,...,...,...,...,...,...,...
5519,Zimbabwe,2021-11-30,133007,4679,8812.980,310.028,3795401.0,2816541.0
5520,Zimbabwe,2021-12-31,135337,4707,8967.370,311.884,4124378.0,3135168.0
5521,Zimbabwe,2022-01-31,214214,5017,14193.700,332.424,4270759.0,3299624.0
5522,Zimbabwe,2022-02-28,229851,5350,15229.800,354.488,4362150.0,3396655.0
5523,Zimbabwe,2022-03-31,236871,5395,15695.000,357.470,4374896.0,3408609.0

In [7]:
for country in range(len(df1.Country.unique())):
      mask = df1.loc[:,'Country']==df1.Country.unique()[country]
      df1[mask]=df1[mask].interpolate(method='linear')

In [8]:
df1.head(50)

,Country,month_date,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,total_vaccinated,total_fully_vaccinated
0,Afghanistan,2020-02-29,5,0,0.126,0.000,NaN,NaN
1,Afghanistan,2020-03-31,5,0,0.126,0.000,NaN,NaN
2,Afghanistan,2020-04-30,192,4,4.820,0.100,NaN,NaN
3,Afghanistan,2020-05-31,2171,64,54.499,1.607,NaN,NaN
4,Afghanistan,2020-06-30,15836,269,397.536,6.753,NaN,NaN
5,Afghanistan,2020-07-31,31848,778,799.489,19.530,NaN,NaN
6,Afghanistan,2020-08-31,36796,1287,923.700,32.308,NaN,NaN
7,Afghanistan,2020-09-30,38282,1410,961.004,35.396,NaN,NaN
8,Afghanistan,2020-10-31,39371,1462,988.341,36.701,NaN,NaN
9,Afghanistan,2020-11-30,41425,1536,1039.900,38.559,NaN,NaN
10,Afghanistan,2020-12-31,46498,1774,1167.250,44.533,NaN,NaN
11,Afghanistan,2021-01-31,52513,2201,1318.250,55.252,NaN,NaN
12,Afghanistan,2021-02-28,55059,2404,1382.160,60.348,8.200000e+03,NaN
13,Afghanistan,2021-03-31,55733,2444,1399.080,61.352,5.400000e+04,NaN
14,Afghanistan,2021-04-30,56517,2489,1418.760,62.482,2.400000e+05,NaN
15,Afghanistan,2021-05-31,59939,2631,1504.670,66.047,4.802260e+05,1.199260e+05
16,Afghanistan,2021-06-30,72977,2973,1831.960,74.632,6.992000e+05,1.876540e+05
17,Afghanistan,2021-07-31,120216,4962,3017.820,124.562,7.429340e+05,2.191590e+05
18,Afghanistan,2021-08-31,147501,6737,3702.760,169.121,7.730020e+05,4.307440e+05
19,Afghanistan,2021-09-30,153260,7123,3847.330,178.811,8.286010e+05,1.350032e+06
20,Afghanistan,2021-10-31,155191,7206,3895.800,180.894,2.179387e+06,2.269321e+06
21,Afghanistan,2021-11-30,156284,7281,3923.240,182.777,3.530173e+06,3.188609e+06
22,Afghanistan,2021-12-31,157359,7309,3950.230,183.480,4.142857e+06,3.753224e+06
23,Afghanistan,2022-01-31,158107,7356,3969.000,184.660,4.554648e+06,3.892831e+06
24,Afghanistan,2022-02-28,163555,7417,4105.770,186.191,4.907058e+06,4.231984e+06
25,Afghanistan,2022-03-31,173879,7609,4364.930,191.011,4.907058e+06,4.231984e+06
26,Albania,2020-02-29,0,0,0.000,0.000,NaN,NaN
27,Albania,2020-03-31,0,0,0.000,0.000,NaN,NaN
28,Albania,2020-04-30,259,15,90.152,5.221,NaN,NaN
29,Albania,2020-05-31,782,31,272.196,10.790,NaN,NaN
30,Albania,2020-06-30,1143,33,397.851,11.487,NaN,NaN
31,Albania,2020-07-31,2580,65,898.037,22.625,NaN,NaN
32,Albania,2020-08-31,5396,161,1878.220,56.040,NaN,NaN
33,Albania,2020-09-30,9606,290,3343.620,100.942,NaN,NaN
34,Albania,2020-10-31,13806,388,4805.540,135.054,NaN,NaN
35,Albania,2020-11-30,21202,518,7379.910,180.303,NaN,NaN
36,Albania,2020-12-31,39014,822,13579.800,286.119,NaN,NaN
37,Albania,2021-01-31,58316,1181,20298.400,411.078,5.490000e+02,NaN
38,Albania,2021-02-28,78992,1393,27495.200,484.870,6.073000e+03,6.550000e+02
39,Albania,2021-03-31,107931,1816,37568.200,632.106,1.660913e+05,9.721433e+04
40,Albania,2021-04-30,125506,2241,43685.700,780.039,3.261097e+05,1.937737e+05
41,Albania,2021-05-31,131185,2396,45662.400,833.991,4.861280e+05,2.903330e+05
42,Albania,2021-06-30,132337,2451,46063.400,853.135,5.645300e+05,4.035040e+05
43,Albania,2021-07-31,132523,2456,46128.100,854.875,6.702150e+05,5.287180e+05
44,Albania,2021-08-31,133121,2457,46336.300,855.223,8.303960e+05,6.419200e+05
45,Albania,2021-09-30,147369,2501,51295.600,870.539,9.464950e+05,7.948780e+05
46,Albania,2021-10-31,170778,2705,59443.800,941.546,1.013959e+06,8.878650e+05
47,Albania,2021-11-30,185497,2931,64567.100,1020.210,1.072645e+06,9.610130e+05
48,Albania,2021-12-31,200173,3101,69675.500,1079.380,1.141486e+06,1.031132e+06
49,Albania,2022-01-31,210224,3217,73174.000,1119.760,1.210040e+06,1.111520e+06

In [9]:
df1.dtypes

Country                      object
month_date                   object
total_cases                   int64
total_deaths                  int64
total_cases_per_million     float64
total_deaths_per_million    float64
total_vaccinated            float64
total_fully_vaccinated      float64
dtype: object

In [10]:
pwd

'C:\\Users\\panam\\OneDrive\\Portfolio_projects\\COVID, wealth, and age'

In [13]:
df1.total_vaccinated.replace(np.nan, 0, inplace=True)
df1.total_fully_vaccinated.replace(np.nan, 0, inplace=True)
df1.head(50)

,Country,month_date,total_cases,total_deaths,total_cases_per_million,total_deaths_per_million,total_vaccinated,total_fully_vaccinated
0,Afghanistan,2020-02-29,5,0,0.126,0.000,0.000000e+00,0.000000e+00
1,Afghanistan,2020-03-31,5,0,0.126,0.000,0.000000e+00,0.000000e+00
2,Afghanistan,2020-04-30,192,4,4.820,0.100,0.000000e+00,0.000000e+00
3,Afghanistan,2020-05-31,2171,64,54.499,1.607,0.000000e+00,0.000000e+00
4,Afghanistan,2020-06-30,15836,269,397.536,6.753,0.000000e+00,0.000000e+00
5,Afghanistan,2020-07-31,31848,778,799.489,19.530,0.000000e+00,0.000000e+00
6,Afghanistan,2020-08-31,36796,1287,923.700,32.308,0.000000e+00,0.000000e+00
7,Afghanistan,2020-09-30,38282,1410,961.004,35.396,0.000000e+00,0.000000e+00
8,Afghanistan,2020-10-31,39371,1462,988.341,36.701,0.000000e+00,0.000000e+00
9,Afghanistan,2020-11-30,41425,1536,1039.900,38.559,0.000000e+00,0.000000e+00
10,Afghanistan,2020-12-31,46498,1774,1167.250,44.533,0.000000e+00,0.000000e+00
11,Afghanistan,2021-01-31,52513,2201,1318.250,55.252,0.000000e+00,0.000000e+00
12,Afghanistan,2021-02-28,55059,2404,1382.160,60.348,8.200000e+03,0.000000e+00
13,Afghanistan,2021-03-31,55733,2444,1399.080,61.352,5.400000e+04,0.000000e+00
14,Afghanistan,2021-04-30,56517,2489,1418.760,62.482,2.400000e+05,0.000000e+00
15,Afghanistan,2021-05-31,59939,2631,1504.670,66.047,4.802260e+05,1.199260e+05
16,Afghanistan,2021-06-30,72977,2973,1831.960,74.632,6.992000e+05,1.876540e+05
17,Afghanistan,2021-07-31,120216,4962,3017.820,124.562,7.429340e+05,2.191590e+05
18,Afghanistan,2021-08-31,147501,6737,3702.760,169.121,7.730020e+05,4.307440e+05
19,Afghanistan,2021-09-30,153260,7123,3847.330,178.811,8.286010e+05,1.350032e+06
20,Afghanistan,2021-10-31,155191,7206,3895.800,180.894,2.179387e+06,2.269321e+06
21,Afghanistan,2021-11-30,156284,7281,3923.240,182.777,3.530173e+06,3.188609e+06
22,Afghanistan,2021-12-31,157359,7309,3950.230,183.480,4.142857e+06,3.753224e+06
23,Afghanistan,2022-01-31,158107,7356,3969.000,184.660,4.554648e+06,3.892831e+06
24,Afghanistan,2022-02-28,163555,7417,4105.770,186.191,4.907058e+06,4.231984e+06
25,Afghanistan,2022-03-31,173879,7609,4364.930,191.011,4.907058e+06,4.231984e+06
26,Albania,2020-02-29,0,0,0.000,0.000,0.000000e+00,0.000000e+00
27,Albania,2020-03-31,0,0,0.000,0.000,0.000000e+00,0.000000e+00
28,Albania,2020-04-30,259,15,90.152,5.221,0.000000e+00,0.000000e+00
29,Albania,2020-05-31,782,31,272.196,10.790,0.000000e+00,0.000000e+00
30,Albania,2020-06-30,1143,33,397.851,11.487,0.000000e+00,0.000000e+00
31,Albania,2020-07-31,2580,65,898.037,22.625,0.000000e+00,0.000000e+00
32,Albania,2020-08-31,5396,161,1878.220,56.040,0.000000e+00,0.000000e+00
33,Albania,2020-09-30,9606,290,3343.620,100.942,0.000000e+00,0.000000e+00
34,Albania,2020-10-31,13806,388,4805.540,135.054,0.000000e+00,0.000000e+00
35,Albania,2020-11-30,21202,518,7379.910,180.303,0.000000e+00,0.000000e+00
36,Albania,2020-12-31,39014,822,13579.800,286.119,0.000000e+00,0.000000e+00
37,Albania,2021-01-31,58316,1181,20298.400,411.078,5.490000e+02,0.000000e+00
38,Albania,2021-02-28,78992,1393,27495.200,484.870,6.073000e+03,6.550000e+02
39,Albania,2021-03-31,107931,1816,37568.200,632.106,1.660913e+05,9.721433e+04
40,Albania,2021-04-30,125506,2241,43685.700,780.039,3.261097e+05,1.937737e+05
41,Albania,2021-05-31,131185,2396,45662.400,833.991,4.861280e+05,2.903330e+05
42,Albania,2021-06-30,132337,2451,46063.400,853.135,5.645300e+05,4.035040e+05
43,Albania,2021-07-31,132523,2456,46128.100,854.875,6.702150e+05,5.287180e+05
44,Albania,2021-08-31,133121,2457,46336.300,855.223,8.303960e+05,6.419200e+05
45,Albania,2021-09-30,147369,2501,51295.600,870.539,9.464950e+05,7.948780e+05
46,Albania,2021-10-31,170778,2705,59443.800,941.546,1.013959e+06,8.878650e+05
47,Albania,2021-11-30,185497,2931,64567.100,1020.210,1.072645e+06,9.610130e+05
48,Albania,2021-12-31,200173,3101,69675.500,1079.380,1.141486e+06,1.031132e+06
49,Albania,2022-01-31,210224,3217,73174.000,1119.760,1.210040e+06,1.111520e+06

In [15]:
df1.to_excel('C:\\Users\\panam\\OneDrive\\Portfolio_projects\\monthly_covid_data.xlsx')