In [1]:
import pandas as pd
import pymysql

# World bank wealth and population data

In [2]:
df = pd.read_excel('Data_Extract_From_World_Development_Indicators.xlsx')
df

,Time,Time Code,Country Name,Country Code,GDP (current US$) [NY.GDP.MKTP.CD],GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],GDP per capita (current US$) [NY.GDP.PCAP.CD],"GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]",Gini index [SI.POV.GINI],"Population ages 65 and above, total [SP.POP.65UP.TO]","Population, total [SP.POP.TOTL]"
0,2012,YR2012,Afghanistan,AFG,19907317065.666649,12.752287,638.845852,1914.774228,..,743602,31161378
1,2012,YR2012,Albania,ALB,12319830437.346674,1.417243,4247.630047,10526.259183,29,330283,2900401
2,2012,YR2012,Algeria,DZA,209058991952.125458,3.4,5592.220115,13303.327519,..,2080797,37383899
3,2012,YR2012,American Samoa,ASM,640000000,-4.334828,11496.524098,..,..,..,55669
4,2012,YR2012,Andorra,AND,3188808942.567133,-4.974444,38686.461264,..,..,..,82427
...,...,...,...,...,...,...,...,...,...,...,...
2170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2173,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2174,Last Updated: 05/25/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#I will start by dropping the reduntant columns Time code and country code
df_1 = df.drop(['Time Code', 'Country Code'], axis = 1)
df_1

,Time,Country Name,GDP (current US$) [NY.GDP.MKTP.CD],GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],GDP per capita (current US$) [NY.GDP.PCAP.CD],"GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]",Gini index [SI.POV.GINI],"Population ages 65 and above, total [SP.POP.65UP.TO]","Population, total [SP.POP.TOTL]"
0,2012,Afghanistan,19907317065.666649,12.752287,638.845852,1914.774228,..,743602,31161378
1,2012,Albania,12319830437.346674,1.417243,4247.630047,10526.259183,29,330283,2900401
2,2012,Algeria,209058991952.125458,3.4,5592.220115,13303.327519,..,2080797,37383899
3,2012,American Samoa,640000000,-4.334828,11496.524098,..,..,..,55669
4,2012,Andorra,3188808942.567133,-4.974444,38686.461264,..,..,..,82427
...,...,...,...,...,...,...,...,...,...
2170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2173,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2174,Last Updated: 05/25/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_1.head()

,Time,Country Name,GDP (current US$) [NY.GDP.MKTP.CD],GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],GDP per capita (current US$) [NY.GDP.PCAP.CD],"GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]",Gini index [SI.POV.GINI],"Population ages 65 and above, total [SP.POP.65UP.TO]","Population, total [SP.POP.TOTL]"
0,2012,Afghanistan,19907317065.666649,12.752287,638.845852,1914.774228,..,743602,31161378
1,2012,Albania,12319830437.346674,1.417243,4247.630047,10526.259183,29,330283,2900401
2,2012,Algeria,209058991952.125458,3.4,5592.220115,13303.327519,..,2080797,37383899
3,2012,American Samoa,640000000,-4.334828,11496.524098,..,..,..,55669
4,2012,Andorra,3188808942.567133,-4.974444,38686.461264,..,..,..,82427

In [5]:
df_1.tail()

,Time,Country Name,GDP (current US$) [NY.GDP.MKTP.CD],GDP growth (annual %) [NY.GDP.MKTP.KD.ZG],GDP per capita (current US$) [NY.GDP.PCAP.CD],"GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]",Gini index [SI.POV.GINI],"Population ages 65 and above, total [SP.POP.65UP.TO]","Population, total [SP.POP.TOTL]"
2170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2173,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2174,Last Updated: 05/25/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_1.columns

Index(['Time', 'Country Name', 'GDP (current US$) [NY.GDP.MKTP.CD]',
       'GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]',
       'GDP per capita (current US$) [NY.GDP.PCAP.CD]',
       'GDP per capita, PPP (current international $) [NY.GDP.PCAP.PP.CD]',
       'Gini index [SI.POV.GINI]',
       'Population ages 65 and above, total [SP.POP.65UP.TO]',
       'Population, total [SP.POP.TOTL]'],
      dtype='object')

In [7]:
#I will rename the columns to make them more intuitive and readable
df_1.columns = ['Year', 'Country', 'GDP (current US$)', 'GDP growth (annual %)',
       'GDP per capita (current US$)', 'GDP per capita, PPP (current international $)',
       'Gini index', 'Population age 65 and over','Total Population']
df_1.columns

Index(['Year', 'Country', 'GDP (current US$)', 'GDP growth (annual %)',
       'GDP per capita (current US$)',
       'GDP per capita, PPP (current international $)', 'Gini index',
       'Population age 65 and over', 'Total Population'],
      dtype='object')

In [8]:
#I wll now remove the rows without country information
df_2 = df_1.dropna()
df_2

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population
0,2012,Afghanistan,19907317065.666649,12.752287,638.845852,1914.774228,..,743602,31161378
1,2012,Albania,12319830437.346674,1.417243,4247.630047,10526.259183,29,330283,2900401
2,2012,Algeria,209058991952.125458,3.4,5592.220115,13303.327519,..,2080797,37383899
3,2012,American Samoa,640000000,-4.334828,11496.524098,..,..,..,55669
4,2012,Andorra,3188808942.567133,-4.974444,38686.461264,..,..,..,82427
...,...,...,...,...,...,...,...,...,...
2165,2021,Virgin Islands (U.S.),..,..,..,..,..,..,..
2166,2021,West Bank and Gaza,..,..,..,..,..,..,..
2167,2021,"Yemen, Rep.",..,..,..,..,..,..,..
2168,2021,Zambia,..,..,..,..,..,..,..
2169,2021,Zimbabwe,..,..,..,..,..,..,..

In [9]:
#check the data types of all columns
df_2.dtypes

Year                                             object
Country                                          object
GDP (current US$)                                object
GDP growth (annual %)                            object
GDP per capita (current US$)                     object
GDP per capita, PPP (current international $)    object
Gini index                                       object
Population age 65 and over                       object
Total Population                                 object
dtype: object

In [10]:
#converting the data types to for easier downstream processing
df_3 = df_2.convert_dtypes()
df_3.dtypes

Year                                              Int64
Country                                          string
GDP (current US$)                                object
GDP growth (annual %)                            object
GDP per capita (current US$)                     object
GDP per capita, PPP (current international $)    object
Gini index                                       object
Population age 65 and over                       object
Total Population                                 object
dtype: object

In [11]:
#Change the 'object datatypes to numeric ones'

df_3 = df_3[['GDP (current US$)', 'GDP growth (annual %)',
       'GDP per capita (current US$)',
       'GDP per capita, PPP (current international $)', 'Gini index',
       'Population aged >= 65', 'Total Population']].apply(pd.to_numeric)
df_3.dtype

KeyError: "['Population aged >= 65'] not in index"

In [12]:
#due to the above error, attempting to convert ".." to Nonetype
df_3 = df_3.replace({'..': None})
df_3

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population
0,2012,Afghanistan,1.990732e+10,12.752287,638.845852,1914.774228,NaN,743602.0,31161378.0
1,2012,Albania,1.231983e+10,1.417243,4247.630047,10526.259183,29.0,330283.0,2900401.0
2,2012,Algeria,2.090590e+11,3.400000,5592.220115,13303.327519,NaN,2080797.0,37383899.0
3,2012,American Samoa,6.400000e+08,-4.334828,11496.524098,NaN,NaN,NaN,55669.0
4,2012,Andorra,3.188809e+09,-4.974444,38686.461264,NaN,NaN,NaN,82427.0
...,...,...,...,...,...,...,...,...,...
2165,2021,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,2021,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2167,2021,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2168,2021,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2169,2021,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_3[['GDP (current US$)', 'GDP growth (annual %)',
       'GDP per capita (current US$)',
       'GDP per capita, PPP (current international $)', 'Gini index',
       'Population age 65 and over', 'Total Population']] = df_3[['GDP (current US$)', 'GDP growth (annual %)',
       'GDP per capita (current US$)',
       'GDP per capita, PPP (current international $)', 'Gini index',
       'Population age 65 and over', 'Total Population']].apply(pd.to_numeric)
df_3.dtypes

Year                                               Int64
Country                                           string
GDP (current US$)                                float64
GDP growth (annual %)                            float64
GDP per capita (current US$)                     float64
GDP per capita, PPP (current international $)    float64
Gini index                                       float64
Population age 65 and over                       float64
Total Population                                 float64
dtype: object

In [14]:
#Converting the 'year' datetype
df_3.Year = pd.to_datetime(df_3.Year, format = '%Y')
df_3

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population
0,2012-01-01,Afghanistan,1.990732e+10,12.752287,638.845852,1914.774228,NaN,743602.0,31161378.0
1,2012-01-01,Albania,1.231983e+10,1.417243,4247.630047,10526.259183,29.0,330283.0,2900401.0
2,2012-01-01,Algeria,2.090590e+11,3.400000,5592.220115,13303.327519,NaN,2080797.0,37383899.0
3,2012-01-01,American Samoa,6.400000e+08,-4.334828,11496.524098,NaN,NaN,NaN,55669.0
4,2012-01-01,Andorra,3.188809e+09,-4.974444,38686.461264,NaN,NaN,NaN,82427.0
...,...,...,...,...,...,...,...,...,...
2165,2021-01-01,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,2021-01-01,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2167,2021-01-01,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2168,2021-01-01,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2169,2021-01-01,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#show only the year in 'Year' col
df_3.Year = pd.DatetimeIndex(df_3.Year).year
df_3

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population
0,2012,Afghanistan,1.990732e+10,12.752287,638.845852,1914.774228,NaN,743602.0,31161378.0
1,2012,Albania,1.231983e+10,1.417243,4247.630047,10526.259183,29.0,330283.0,2900401.0
2,2012,Algeria,2.090590e+11,3.400000,5592.220115,13303.327519,NaN,2080797.0,37383899.0
3,2012,American Samoa,6.400000e+08,-4.334828,11496.524098,NaN,NaN,NaN,55669.0
4,2012,Andorra,3.188809e+09,-4.974444,38686.461264,NaN,NaN,NaN,82427.0
...,...,...,...,...,...,...,...,...,...
2165,2021,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,2021,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2167,2021,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2168,2021,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2169,2021,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#create a column calculating the % of the population made up of individuals over 65
df_3['% of population 65 and over'] = df_3['Population age 65 and over']/df_3['Total Population'] * 100
df_3

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population,% of population 65 and over
0,2012,Afghanistan,1.990732e+10,12.752287,638.845852,1914.774228,NaN,743602.0,31161378.0,2.386294
1,2012,Albania,1.231983e+10,1.417243,4247.630047,10526.259183,29.0,330283.0,2900401.0,11.387494
2,2012,Algeria,2.090590e+11,3.400000,5592.220115,13303.327519,NaN,2080797.0,37383899.0,5.566025
3,2012,American Samoa,6.400000e+08,-4.334828,11496.524098,NaN,NaN,NaN,55669.0,NaN
4,2012,Andorra,3.188809e+09,-4.974444,38686.461264,NaN,NaN,NaN,82427.0,NaN
...,...,...,...,...,...,...,...,...,...,...
2165,2021,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,2021,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2167,2021,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2168,2021,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2169,2021,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#check the amount of data in 2021 as it seems mostly null from the above
df_2021 = df_3.loc[df_3['Year'] == 2021]
df_2021

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population,% of population 65 and over
1953,2021,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1954,2021,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1955,2021,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1956,2021,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1957,2021,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2165,2021,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,2021,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2167,2021,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2168,2021,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2169,2021,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#I want to be able to see all of the above rows
pd.set_option('display.max_rows', None)
df_2021

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population,% of population 65 and over
1953,2021,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1954,2021,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1955,2021,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1956,2021,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1957,2021,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1958,2021,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959,2021,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1960,2021,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1961,2021,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962,2021,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963,2021,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964,2021,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1965,2021,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1966,2021,"Bahamas, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,2021,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,2021,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1969,2021,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970,2021,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1971,2021,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1972,2021,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1973,2021,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974,2021,Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975,2021,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,2021,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1977,2021,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1978,2021,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1979,2021,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,2021,British Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981,2021,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982,2021,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983,2021,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1984,2021,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1985,2021,Cabo Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986,2021,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1987,2021,Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988,2021,Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1989,2021,Cayman Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,2021,Central African Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991,2021,Chad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1992,2021,Channel Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1993,2021,Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1994,2021,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995,2021,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,2021,Comoros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,2021,"Congo, Dem. Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,2021,"Congo, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,2021,Costa Rica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000,2021,Cote d'Ivoire,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001,2021,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002,2021,Cuba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003,2021,Curacao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,2021,Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,2021,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,2021,Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,2021,Djibouti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2008,2021,Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009,2021,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,2021,Ecuador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011,2021,"Egypt, Arab Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012,2021,El Salvador,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013,2021,Equatorial Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,2021,Eritrea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,2021,Estonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,2021,Eswatini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017,2021,Ethiopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018,2021,Faroe Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019,2021,Fiji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020,2021,Finland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,2021,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022,2021,French Polynesia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023,2021,Gabon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024,2021,"Gambia, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025,2021,Georgia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026,2021,Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2027,2021,Ghana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028,2021,Gibraltar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2029,2021,Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2030,2021,Greenland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2031,2021,Grenada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2032,2021,Guam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2033,2021,Guatemala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2034,2021,Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2035,2021,Guinea-Bissau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2036,2021,Guyana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2037,2021,Haiti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2038,2021,Honduras,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039,2021,"Hong Kong SAR, China",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2040,2021,Hungary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2041,2021,Iceland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2042,2021,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2043,2021,Indonesia,NaN,NaN,NaN,NaN,37.3,NaN,NaN,NaN
2044,2021,"Iran, Islamic Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2045,2021,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2046,2021,Ireland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2047,2021,Isle of Man,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2048,2021,Israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2049,2021,Italy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2050,2021,Jamaica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2051,2021,Japan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2052,2021,Jordan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2053,2021,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2054,2021,Kenya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2055,2021,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2056,2021,"Korea, Dem. People's Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2057,2021,"Korea, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2058,2021,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2059,2021,Kuwait,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2060,2021,Kyrgyz Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2061,2021,Lao PDR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2062,2021,Latvia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2063,2021,Lebanon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2064,2021,Lesotho,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2065,2021,Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2066,2021,Libya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2067,2021,Liechtenstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2068,2021,Lithuania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2069,2021,Luxembourg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2070,2021,"Macao SAR, China",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2071,2021,Madagascar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2072,2021,Malawi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2073,2021,Malaysia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2074,2021,Maldives,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2075,2021,Mali,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2076,2021,Malta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2077,2021,Marshall Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2078,2021,Mauritania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2079,2021,Mauritius,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2080,2021,Mexico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2081,2021,"Micronesia, Fed. Sts.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2082,2021,Moldova,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2083,2021,Monaco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2084,2021,Mongolia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2085,2021,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2086,2021,Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2087,2021,Mozambique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2088,2021,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2089,2021,Namibia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2090,2021,Nauru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2091,2021,Nepal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092,2021,Netherlands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2093,2021,New Caledonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2094,2021,New Zealand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2095,2021,Nicaragua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2096,2021,Niger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2097,2021,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2098,2021,North Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2099,2021,Northern Mariana Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2100,2021,Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2101,2021,Oman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2102,2021,Pakistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2103,2021,Palau,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2104,2021,Panama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2105,2021,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2106,2021,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2107,2021,Peru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2108,2021,Philippines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2109,2021,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2110,2021,Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2111,2021,Puerto Rico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2112,2021,Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2113,2021,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2114,2021,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2115,2021,Rwanda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2116,2021,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2117,2021,San Marino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2118,2021,Sao Tome and Principe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2119,2021,Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2120,2021,Senegal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2121,2021,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2122,2021,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2123,2021,Sierra Leone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2124,2021,Singapore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2125,2021,Sint Maarten (Dutch part),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2126,2021,Slovak Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2127,2021,Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2128,2021,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2129,2021,Somalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2130,2021,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2131,2021,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2132,2021,Spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2133,2021,Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2134,2021,St. Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2135,2021,St. Lucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2136,2021,St. Martin (French part),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2137,2021,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2138,2021,Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2139,2021,Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2140,2021,Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2141,2021,Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2142,2021,Syrian Arab Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2143,2021,Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2144,2021,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2145,2021,Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2146,2021,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2147,2021,Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2148,2021,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2149,2021,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2150,2021,Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2151,2021,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2152,2021,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2153,2021,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2154,2021,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2155,2021,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2156,2021,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157,2021,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2158,2021,United Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2159,2021,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2160,2021,Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2161,2021,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2162,2021,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2163,2021,"Venezuela, RB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2164,2021,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2165,2021,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2166,2021,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2167,2021,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2168,2021,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2169,2021,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#none of the countries have data from 2021, therefore, will delete the year in dataframe
df_4 = df_3[df_3.Year != 2021]
df_4.head()

,Year,Country,GDP (current US$),GDP growth (annual %),GDP per capita (current US$),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population,% of population 65 and over
0,2012,Afghanistan,1.990732e+10,12.752287,638.845852,1914.774228,NaN,743602.0,31161378.0,2.386294
1,2012,Albania,1.231983e+10,1.417243,4247.630047,10526.259183,29.0,330283.0,2900401.0,11.387494
2,2012,Algeria,2.090590e+11,3.400000,5592.220115,13303.327519,NaN,2080797.0,37383899.0,5.566025
3,2012,American Samoa,6.400000e+08,-4.334828,11496.524098,NaN,NaN,NaN,55669.0,NaN
4,2012,Andorra,3.188809e+09,-4.974444,38686.461264,NaN,NaN,NaN,82427.0,NaN

In [20]:
#GDP per capita and GDP PPP are similar in what they convey. However, PPP is more informative
#I will now remove GDP per capita from the data frame
df_4.columns

Index(['Year', 'Country', 'GDP (current US$)', 'GDP growth (annual %)',
       'GDP per capita (current US$)',
       'GDP per capita, PPP (current international $)', 'Gini index',
       'Population age 65 and over', 'Total Population',
       '% of population 65 and over'],
      dtype='object')

In [21]:
df_5 = df_4.drop(['GDP per capita (current US$)'], axis = 1)
df_5.head()

,Year,Country,GDP (current US$),GDP growth (annual %),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population,% of population 65 and over
0,2012,Afghanistan,1.990732e+10,12.752287,1914.774228,NaN,743602.0,31161378.0,2.386294
1,2012,Albania,1.231983e+10,1.417243,10526.259183,29.0,330283.0,2900401.0,11.387494
2,2012,Algeria,2.090590e+11,3.400000,13303.327519,NaN,2080797.0,37383899.0,5.566025
3,2012,American Samoa,6.400000e+08,-4.334828,NaN,NaN,NaN,55669.0,NaN
4,2012,Andorra,3.188809e+09,-4.974444,NaN,NaN,NaN,82427.0,NaN

In [22]:
#I dont need to keep seeing the whole database
pd.set_option('display.max_rows', 10)

In [23]:
#to export the data frame to an sql data table
conn = pymysql.connect(host = 'localhost', database = 'covid_and_wealth', user = 'root', password = 'mADZIVIRE1996')
cursor = conn.cursor()

In [24]:
def CreateTable(df,SQL_table):
    insert_query = f'INSERT INTO {SQL_table} VALUES'
    values_array = df.values
    df_values_export =[]

    for row in values_array:
        df_values_export.append(tuple(row))
    insert_query +=str(df_values_export)[1:-1] + ';'
    

    return insert_query

In [25]:
cursor.execute(CreateTable(df_5, 'national_wealth_data'))

OperationalError: (1054, "Unknown column 'nan' in 'field list'")

In [26]:
#due to the above error, tryin to convert values stored as NaN to none
df_6 = df_5.where(pd.notnull(df_5), '')
df_6

,Year,Country,GDP (current US$),GDP growth (annual %),"GDP per capita, PPP (current international $)",Gini index,Population age 65 and over,Total Population,% of population 65 and over
0,2012,Afghanistan,19907317065.666649,12.752287,1914.774228,,743602.0,31161378.0,2.386294
1,2012,Albania,12319830437.346674,1.417243,10526.259183,29.0,330283.0,2900401.0,11.387494
2,2012,Algeria,209058991952.125458,3.4,13303.327519,,2080797.0,37383899.0,5.566025
3,2012,American Samoa,640000000.0,-4.334828,,,,55669.0,
4,2012,Andorra,3188808942.567133,-4.974444,,,,82427.0,
...,...,...,...,...,...,...,...,...,...
1948,2020,Virgin Islands (U.S.),,,,,21785.0,106290.0,20.495813
1949,2020,West Bank and Gaza,15561300000.0,-11.457452,5689.945334,,154473.0,4803269.0,3.215997
1950,2020,"Yemen, Rep.",,,,,874194.0,29825968.0,2.930983
1951,2020,Zambia,18110631358.31139,-2.785055,3457.610102,,391950.0,18383956.0,2.132022
1952,2020,Zimbabwe,18051170798.941048,-6.248748,3537.351394,,447995.0,14862927.0,3.014177

In [27]:
cursor.execute(CreateTable(df_6, 'national_wealth_data'))

1953

In [28]:
conn.commit()

In [29]:
conn.close()